name: Changelog Generator

on:
  push:
    branches: [ main ]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Update changelog
    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changelog file changes
        env:
          CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
          CI_EMAIL: ${{ secrets.YOUR_GITHUB_EMAIL }}
        run: |
          git config --local user.email "shahnh19@gmail.com"
          git config --local user.name "NeelayS"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

      - name: Push changes
        if: env.push == 'true'
        env:
          CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:main